### PR TITLE
Polish README and opam files

### PR DESCRIPTION
**Pull request by jmid**
This PR
- updates the README to reflect the latest Base-renaming and a few other things like 80-column width
- adds a version and a few tags to the opam files
- adds Samuel as co-author

Version-wise, I put `"0.1"` which signals a bit of maturity but not a lot.

### CODE REVIEW

**Comment by n-osborne** [comment]
In commit [f276262](https://github.com/jmid/multicoretests/pull/220/commits/f276262d9c25656e8d919e4f03fa9a771649b7ea) and  [71c4d6e](https://github.com/jmid/multicoretests/pull/220/commits/71c4d6e43aad415b6360c5d32247d7e57160eb8c) you edit some opam file, but IIRC that in #127 we have switched to generating opam files from the dune-project.

**Comment by jmid** [comment]
Well spotted! I had completely forgotten again (and missed the `autogenerated file` warnings at the top somehow :sweat_smile: )

**Comment by jmid** [comment]
Here is a second attempt making the changes to the `dune-project` file instead.
While doing so, I spotted some dependencies that hadn't been updated in there...

Note to self (and any others wondering): `opam build` will not regenerate the opam-files but `opam build @all` will.

**Comment by jmid** [comment]
CI is relatively happy, so I'll merge this.

**Pull request merged**
